-- 배포 전에 운영 DB에서 1회 실행한다.
-- 중복 이메일/닉네임이 이미 있으면 unique 제약 추가가 실패하므로 먼저 정리해야 한다.

ALTER TABLE TM_USERXM MODIFY (PASS_WORD VARCHAR2(255));

DECLARE
    V_START NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(SUBSTR(USER_NUMB, 7, 4))), 0) + 1
     INTO V_START
      FROM TM_USERXM
     WHERE REGEXP_LIKE(USER_NUMB, '^UR[0-9]{8}$')
       AND SUBSTR(USER_NUMB, 3, 4) = TO_CHAR(SYSDATE, 'YYMM');
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SQ_GATHER_USER START WITH ' || V_START ||
                      ' INCREMENT BY 1 MAXVALUE 9999 CYCLE CACHE 50';
END;
/

DECLARE
    V_START NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(SUBSTR(MOIM_IDXX, 7, 4))), 0) + 1
      INTO V_START
      FROM TM_MOIMXM
     WHERE REGEXP_LIKE(MOIM_IDXX, '^[A-Z]{2}[0-9]{8}$')
       AND SUBSTR(MOIM_IDXX, 3, 4) = TO_CHAR(SYSDATE, 'YYMM');
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SQ_GATHER_MOIM START WITH ' || V_START ||
                      ' INCREMENT BY 1 MAXVALUE 9999 CYCLE CACHE 50';
END;
/

ALTER TABLE TM_USERXM ADD CONSTRAINT UK_TM_USERXM_IDXX UNIQUE (USER_IDXX);
ALTER TABLE TM_USERXM ADD CONSTRAINT UK_TM_USERXM_NICK UNIQUE (USER_NICK);

ALTER TABLE TB_FOLLOW ADD CONSTRAINT UK_TB_FOLLOW_PAIR UNIQUE (USER_NUMB, FOLW_USER);
ALTER TABLE TM_HEARTS ADD CONSTRAINT UK_TM_HEARTS_PAIR UNIQUE (LIKE_IDXX, USER_NUMB);
ALTER TABLE TB_MEMBER ADD CONSTRAINT UK_TB_MEMBER_PAIR UNIQUE (MOIM_IDXX, USER_NUMB);

CREATE INDEX IX_TB_NOTIFY_USER_READ ON TB_NOTIFY (USER_NUMB, READ_YSNO, REGG_DATE);
CREATE INDEX IX_TB_HASHTG_IDXX ON TB_HASHTG (HASH_IDXX, HASH_SEQC);
